# Generated by Django 3.2.8 on 2021-11-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_alter_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='num',
            field=models.IntegerField(null=20, verbose_name='可容納人數'),
        ),
    ]
