# Generated by Django 3.2.8 on 2021-11-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20211105_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='num',
            field=models.IntegerField(verbose_name=20),
        ),
    ]
