# Generated by Django 3.2.8 on 2021-12-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_alter_room_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sessionMember',
            field=models.ManyToManyField(blank=True, related_name='members', to='loginapp.customer'),
        ),
    ]
